"""Option maps the plugin declares, as enums."""

from __future__ import annotations

from enum import IntEnum, IntFlag


class SystemState(IntEnum):
    """System State."""

    WAITING = 0
    CHECKING = 1
    GRID_CONNECTED = 2
    EMERGENCY_POWER_SUPPLY = 3
    RECOVERABLE_FAULT = 4
    PERMANENT_FAULT = 5
    UPGRADING = 6
    SELF_CHARGING = 7


class Fault1(IntFlag):
    """Fault 1."""

    ID01_GRID_OVER_VOLTAGE_PROTECTION = 1
    ID02_GRID_UNDER_VOLTAGE_PROTECTION = 2
    ID03_GRID_OVER_FREQUENCY_PROTECTION = 4
    ID04_GRID_UNDER_FREQUENCY_PROTECTION = 8
    ID05_LEAKAGE_CURRENT_FAULT = 16
    ID06_HIGH_PENETRATION_ERROR = 32
    ID07_LOW_PENETRATION_ERROR = 64
    ID08_ISLANDING_ERROR = 128
    ID09_GRID_VOLTAGE_TRANSIENT_VALUE_OVERVOLTAGE_1 = 256
    ID10_GRID_VOLTAGE_TRANSIENT_VALUE_OVERVOLTAGE_2 = 512
    ID11_GRID_LINE_VOLTAGE_ERROR = 1024
    ID12_INVERTER_VOLTAGE_ERROR = 2048


class Fault2(IntFlag):
    """Fault 2."""

    ID17_GRID_CURRENT_SAMPLING_ERROR = 1
    ID18_GRID_CURRENT_DC_COMPONENT_SAMPLING_ERROR_AC_SIDE = 2
    ID19_GRID_VOLTAGE_SAMPLING_ERROR_DC_SIDE = 4
    ID20_GRID_VOLTAGE_SAMPLING_ERROR_AC_SIDE = 8
    ID21_LEAKAGE_CURRENT_SAMPLING_ERROR_DC_SIDE = 16
    ID22_LEAKAGE_CURRENT_SAMPLING_ERROR_AC_SIDE = 32
    ID23_LOAD_VOLTAGE_DC_COMPONENT_SAMPLING_ERROR = 64
    ID24_DC_INPUT_CURRENT_SAMPLING_ERROR = 128
    ID25_DC_COMPONENT_SAMPLING_ERROR_OF_GRID_CURRENT_DC_SIDE = 256
    ID26_DC_INPUT_BRANCH_CURRENT_SAMPLING_ERROR = 512
    ID29_LEAKAGE_CURRENT_CONSISTENCY_ERROR = 4096
    ID30_GRID_VOLTAGE_CONSISTENCY_ERROR = 8192
    ID31_DCI_CONSISTENCY_ERROR = 16384


class Fault3(IntFlag):
    """Fault 3."""

    ID033_SPI_COMMUNICATION_ERROR_DC_SIDE = 1
    ID034_SPI_COMMUNICATION_ERROR_AC_SIDE = 2
    ID035_CHIP_ERROR_DC_SIDE = 4
    ID036_CHIP_ERROR_AC_SIDE = 8
    ID037_AUXILIARY_POWER_ERROR = 16
    ID038_INVERTER_SOFT_START_FAILURE = 32
    ID041_RELAY_DETECTION_FAILURE = 256
    ID042_LOW_INSULATION_IMPEDANCE = 512
    ID043_GROUNDING_ERROR = 1024
    ID044_INPUT_MODE_SETTING_ERROR = 2048
    ID045_ID045_CT_ERROR = 4096
    ID046_INPUT_REVERSAL_ERROR = 8192
    ID047_PARALLEL_ERROR = 16384
    ID048_SERIAL_NUMBER_ERROR = 32768


class Fault4(IntFlag):
    """Fault 4."""

    ID049_BATTERY_TEMPERATURE_PROTECTION = 1
    ID050_HEAT_SINK_1_TEMPERATURE_PROTECTION = 2
    ID051_HEATER_2_TEMPERATURE_PROTECTION = 4
    ID052_HEATER_3_TEMPERATURE_PROTECTION = 8
    ID053_HEATSINK_4_TEMPERATURE_PROTECTION = 16
    ID054_HEATSINK_5_TEMPERATURE_PROTECTION = 32
    ID055_RADIATOR_6_TEMPERATURE_PROTECTION = 64
    ID057_AMBIENT_TEMPERATURE_1_PROTECTION = 256
    ID058_AMBIENT_TEMPERATURE_2_PROTECTION = 512
    ID059_MODULE_1_TEMPERATURE_PROTECTION = 1024
    ID060_MODULE_2_TEMPERATURE_PROTECTION = 2048
    ID061_MODULE_3_TEMPERATURE_PROTECTION = 4096
    ID062_MODULE_TEMPERATURE_DIFFERENCE_IS_TOO_LARGE = 8192


class Fault5(IntFlag):
    """Fault 5."""

    ID065_BUS_VOLTAGE_RMS_UNBALANCE = 1
    ID066_BUS_VOLTAGE_TRANSIENT_VALUE_UNBALANCE = 2
    ID067_UNDERVOLTAGE_OF_BUSBAR_DURING_GRID_CONNECTION = 4
    ID068_BUS_BAR_LOW_VOLTAGE = 8
    ID069_PV_OVERVOLTAGE = 16
    ID070_BATTERY_OVER_VOLTAGE = 32
    ID071_LLCBUS_OVERVOLTAGE_PROTECTION = 64
    ID072_INVERTER_BUS_VOLTAGE_RMS_SOFTWARE_OVERVOLTAGE = 128
    ID073_INVERTER_BUS_VOLTAGE_TRANSIENT_VALUE_SOFTWARE_OVERVOLTAGE = 256
    ID074_FLYING_CROSS_CAPACITOR_OVERVOLTAGE_PROTECTION = 512
    ID075_FLYING_CROSS_CAPACITOR_UNDERVOLTAGE_PROTECTION = 1024


class Fault6(IntFlag):
    """Fault 6."""

    ID081_BATTERY_OVERCURRENT_SOFTWARE_PROTECTION = 1
    ID082_DCI_OVERCURRENT_PROTECTION = 2
    ID083_OUTPUT_TRANSIENT_CURRENT_PROTECTION = 4
    ID084_BUCKBOOST_SOFTWARE_OVERCURRENT = 8
    ID085_OUTPUT_RMS_CURRENT_PROTECTION = 16
    ID086_PV_INSTANTANEOUS_CURRENT_OVERCURRENT_SOFTWARE_PROTECTION = 32
    ID087_PV_PARALLEL_UNEVEN_CURRENT = 64
    ID088_OUTPUT_CURRENT_UNBALANCE = 128
    ID089_PV_SOFTWARE_OVERCURRENT_PROTECTION = 256
    ID090_BALANCED_CIRCUIT_OVERCURRENT_PROTECTION = 512
    ID091_RESONANCE_PROTECTION = 1024


class Fault7(IntFlag):
    """Fault 7."""

    ID097_LLC_BUS_HARDWARE_OVERVOLTAGE = 1
    ID098_INVERTER_BUS_HARDWARE_OVERVOLTAGE = 2
    ID099_BUCKBOOST_HARDWARE_OVERCURRENT = 4
    ID100_BATTERY_HARDWARE_OVERCURRENT = 8
    ID101 = 16
    ID102_PV_HARDWARE_OVERCURRENT = 32
    ID103_AC_OUTPUT_HARDWARE_OVERCURRENT = 64
    ID105_POWER_METER_ERROR = 256
    ID106_SERIAL_NUMBER_MODEL_ERROR = 512
    ID110_OVERLOAD_PROTECTION_1 = 8192
    ID111_OVERLOAD_PROTECTION_2 = 16384
    ID112_OVERLOAD_PROTECTION_3 = 32768


class Fault8(IntFlag):
    """Fault 8."""

    ID113_OVERTEMPERATURE_DERATING = 1
    ID114_FREQUENCY_DOWN_LOAD = 2
    ID115_FREQUENCY_LOADING = 4
    ID116_VOLTAGE_DOWN_LOAD = 8
    ID117_VOLTAGE_LOADING = 16
    ID121_LIGHTNING_PROTECTION_FAILURE_DC = 256
    ID122_LIGHTNING_PROTECTION_FAILURE_AC = 512
    ID124_BATTERY_LOW_VOLTAGE_PROTECTION = 2048
    ID125_BATTERY_LOW_VOLTAGE_SHUTDOWN = 4096
    ID126_BATTERY_LOW_VOLTAGE_PRE_ALARM = 8192


class Fault9(IntFlag):
    """Fault 9."""

    ID129_OUTPUT_HARDWARE_OVERCURRENT_PERMANENT_FAULT = 1
    ID130_BUS_OVERVOLTAGE_PERMANENT_FAULT = 2
    ID131_BUS_HARDWARE_OVER_VOLTAGE_PERMANENT_FAULT = 4
    ID132_PV_UNEVEN_FLOW_PERMANENT_FAULT = 8
    ID133_BATTERY_OVERCURRENT_PERMANENT_FAULT_IN_EPS_MODE = 16
    ID134_OUTPUT_TRANSIENT_OVERCURRENT_PERMANENT_FAULT = 32
    ID135_OUTPUT_CURRENT_UNBALANCE_PERMANENT_FAULT = 64
    ID137_INPUT_MODE_SETTING_ERROR_PERMANENT_FAULT = 256
    ID138_INPUT_OVERCURRENT_PERMANENT_FAULT = 512
    ID139_INPUT_HARDWARE_OVERCURRENT_PERMANENT_FAULT = 1024
    ID140_RELAY_PERMANENT_FAULT = 2048
    ID141_BUS_UNBALANCE_PERMANENT_FAULT = 4096
    ID142_LIGHTNING_PROTECTION_PERMANENT_FAULT_DC_SIDE = 8192
    ID143_LIGHTNING_PROTECTION_PERMANENT_FAULT_AC_SIDE = 16384


class Fault10(IntFlag):
    """Fault 10."""

    ID145_USB_FAULT = 1
    ID146_WIFI_FAULT = 2
    ID147_BLUETOOTH_FAULT = 4
    ID148_RTC_CLOCK_FAULT = 8
    ID149_COMMUNICATION_BOARD_EEPROM_ERROR = 16
    ID150_COMMUNICATION_BOARD_FLASH_ERROR = 32
    ID152_SAFETY_REGULATION_VERSION_ERROR = 128
    ID153_SCI_COMMUNICATION_ERROR_DC_SIDE = 256
    ID154_SCI_COMMUNICATION_ERROR_AC_SIDE = 512
    ID155_SCI_COMMUNICATION_ERROR_CONVERGENCE_BOARD_SIDE = 1024
    ID156_SOFTWARE_VERSION_INCONSISTENCY = 2048
    ID157_LITHIUM_BATTERY_1_COMMUNICATION_ERROR = 4096
    ID158_LI_ION_BATTERY_2_COMMUNICATION_ERROR = 8192
    ID159_LITHIUM_BATTERY_3_COMMUNICATION_ERROR = 16384
    ID160_LITHIUM_BATTERY_4_COMMUNICATION_FAILURE = 32768


class Fault11(IntFlag):
    """Fault 11."""

    ID161_FORCED_SHUTDOWN = 1
    ID162_REMOTE_SHUTDOWN = 2
    ID163_DRMS0_SHUTDOWN = 4
    ID165_REMOTE_DOWN_LOAD = 16
    ID166_LOGIC_INTERFACE_DOWN_LOAD = 32
    ID167_ANTI_REVERSE_FLOW_DOWNGRADE = 64
    ID169_FAN_1_FAILURE = 256
    ID170_FAN_2_FAILURE = 512
    ID171_FAN_3_FAILURE = 1024
    ID172_FAN_4_FAILURE = 2048
    ID173_FAN_5_FAILURE = 4096
    ID174_FAN_6_FAILURE = 8192
    ID175_FAN_7_FAULT = 16384
    ID176_METER_COMMUNICATION_FAILURE = 32768


class Fault12(IntFlag):
    """Fault 12."""

    ID177_BMS_OVER_VOLTAGE_ALARM = 1
    ID178_BMS_UNDERVOLTAGE_ALARM = 2
    ID179_BMS_HIGH_TEMPERATURE_ALARM = 4
    ID180_BMS_LOW_TEMPERATURE_ALARM = 8
    ID181_BMS_CHARGE_DISCHARGE_OVERLOAD_ALARM = 16
    ID182_BMS_SHORT_CIRCUIT_ALARM = 32
    ID183_BMS_VERSION_INCONSISTENCY = 64
    ID184_BMS_CAN_VERSION_INCONSISTENCY = 128
    ID185_BMS_CAN_VERSION_IS_TOO_LOW = 256
    ID189_ARC_DEVICE_COMMUNICATION_FAILURE = 4096
    ID190_DC_ARC_ALARM_FAULT = 8192
    ID191_PID_REPAIR_FAILED = 16384
    ID192_PLC_MODULE_HEARTBEAT_LOSS = 32768


class SyncRtcResult(IntEnum):
    """Update System Time Operation Result."""

    SUCCESSFUL = 0
    OPERATION_IN_PROGRESS = 1
    ENABLED_DISCHARGING = 2
    DISABLED = 4
    OPERATION_FAILED_CONTROLLER_REFUSED_TO_RESPOND = 65531
    OPERATION_FAILED_NO_RESPONSE_FROM_THE_CONTROLLER = 65532
    OPERATION_FAILED_CURRENT_FUNCTION_DISABLED = 65533
    OPERATION_FAILED_PARAMETER_ACCESS_FAILED = 65534
    OPERATION_FAILED_INPUT_PARAMETERS_INCORRECT = 65535


class FeedinLimitationMode(IntEnum):
    """FeedIn: Limitation Mode."""

    DISABLED = 0
    ENABLED_FEED_IN_LIMITATION = 1
    ENABLED_3_PHASE_LIMIT = 2


class EpsControlMode(IntEnum):
    """EPS Mode."""

    TURN_OFF = 0
    TURN_ON_PROHIBIT_COLD_START = 1
    TURN_ON_ENABLE_COLD_START = 2


class ParallelMasterslave(IntEnum):
    """Parallel Master-Salve."""

    SLAVE = 0
    MASTER = 1


class BatConfigProtocol(IntEnum):
    """BatConfig: Protocol."""

    FIRST_FLIGHT_BUILT_IN_BMS_DEFAULT = 0
    PIE_ENERGY_PROTOCOL_PYLON = 1
    FIRST_FLIGHT_PROTOCOL_GENERAL = 2
    AMASS = 3
    LG = 4
    ALPHAESS = 5
    CATL = 6
    WECO = 7
    FRONUS = 8
    EMS = 9
    NILAR = 10
    BTS_5K = 11
    MOVE_FOR = 12


class BatConfigCellType(IntEnum):
    """BatConfig: Cell Type."""

    LEAD_ACID = 0
    LITHIUM_IRON_PHOSPHATE = 1
    TERNARY = 2
    LITHIUM_TITANATE = 3
    AGM = 4
    GEL = 5
    FLOODED = 6


class RemoteSwitchOnOff(IntEnum):
    """Remote Switch On Off."""

    OFF = 0
    ON = 1


class ChargerUseMode(IntEnum):
    """Charger Use Mode."""

    SELF_USE = 0
    TIME_OF_USE = 1
    TIMING_MODE = 2
    PASSIVE_MODE = 3
    PEAK_CUT_MODE = 4
    OFF_GRID_MODE = 5
    GENERATOR_MODE = 6
    FEED_IN_PRIORITY_MODE = 7


class PassiveModeTimeoutAction(IntEnum):
    """Passive: Timeout Action."""

    FORCE_STANDBY = 0
    RETURN_TO_PREVIOUS_MODE = 1


class PowerControlFlags(IntFlag):
    """Power_Control (register 1105) — which real-time control registers apply.

    The device only acts on 1106-1109 while the matching bit here is set. Bits
    1-4 (reactive power, power factor mode, SVG) are not modelled: nothing in
    this library writes them yet.
    """

    ACTIVE_POWER = 1 << 0
    """Apply Active_Power_Export_Limit (1106)."""
